<?php

/**
 * This file is part of "School of Super Powers" Project.
 *
 * @author (c) José Cândido Pereira da Rocha <josecprocha@gmail.com>
 *
 * This source file is subject to the {@license ISC} license that is bundled
 * with this source code in the file LICENSE.md. Source is available in {@link
 * https://github.com/josecprocha/superpowers}.
 *
 * Made with Laravel — {@see https://github.com/laravel/laravel to know more
 * about this framework}.
 */

namespace Database\Migrations\Insertions;

//localization;

DB::table('countries')->insert([
    [
        'id' => 'AF',
        'iso_a1' => 4,
        'iso_a3' => 'AFG',
        'country_name' => 'Afghanistan',
    ],
    [
        'id' => 'AL',
        'iso_a1' => 8,
        'iso_a3' => 'AFG',
        'country_name' => 'Albania',
    ],
    [
        'id' => 'AQ',
        'iso_a1' => 10,
        'iso_a3' => 'AFG',
        'country_name' => 'Antarctica',
    ],
    [
        'id' => 'DZ',
        'iso_a1' => 12,
        'iso_a3' => 'AFG',
        'country_name' => 'Algeria',
    ],
    [
        'id' => 'AS',
        'iso_a1' => 16,
        'iso_a3' => 'AFG',
        'country_name' => 'American Samoa',
    ],
    [
        'id' => 'AD',
        'iso_a1' => 20,
        'iso_a3' => 'AFG',
        'country_name' => 'Andorra',
    ],
    [
        'id' => 'AO',
        'iso_a1' => 24,
        'iso_a3' => 'AFG',
        'country_name' => 'Angola',
    ],
    [
        'id' => 'AG',
        'iso_a1' => 28,
        'iso_a3' => 'AFG',
        'country_name' => 'Antigua and Barbuda',
    ],
    [
        'id' => 'AZ',
        'iso_a1' => 31,
        'iso_a3' => 'AFG',
        'country_name' => 'Azerbaijan',
    ],
    [
        'id' => 'AR',
        'iso_a1' => 32,
        'iso_a3' => 'AFG',
        'country_name' => 'Argentina',
    ],
    [
        'id' => 'AU',
        'iso_a1' => 36,
        'iso_a3' => 'AFG',
        'country_name' => 'Australia',
    ],
    [
        'id' => 'AT',
        'iso_a1' => 40,
        'iso_a3' => 'AFG',
        'country_name' => 'Austria',
    ],
    [
        'id' => 'BS',
        'iso_a1' => 44,
        'iso_a3' => 'AFG',
        'country_name' => 'Bahamas',
    ],
    [
        'id' => 'BH',
        'iso_a1' => 48,
        'iso_a3' => 'AFG',
        'country_name' => 'Bahrain',
    ],
    [
        'id' => 'BD',
        'iso_a1' => 50,
        'iso_a3' => 'AFG',
        'country_name' => 'Bangladesh',
    ],
    [
        'id' => 'AM',
        'iso_a1' => 51,
        'iso_a3' => 'AFG',
        'country_name' => 'Armenia',
    ],
    [
        'id' => 'BB',
        'iso_a1' => 52,
        'iso_a3' => 'AFG',
        'country_name' => 'Barbados',
    ],
    [
        'id' => 'BE',
        'iso_a1' => 56,
        'iso_a3' => 'AFG',
        'country_name' => 'Belgium',
    ],
    [
        'id' => 'BM',
        'iso_a1' => 60,
        'iso_a3' => 'AFG',
        'country_name' => 'Bermuda',
    ],
    [
        'id' => 'BT',
        'iso_a1' => 64,
        'iso_a3' => 'AFG',
        'country_name' => 'Bhutan',
    ],
    [
        'id' => 'BO',
        'iso_a1' => 68,
        'iso_a3' => 'AFG',
        'country_name' => 'Bolivia',
    ],
    [
        'id' => 'BA',
        'iso_a1' => 70,
        'iso_a3' => 'AFG',
        'country_name' => 'Bosnia and Herzegovina',
    ],
    [
        'id' => 'BW',
        'iso_a1' => 72,
        'iso_a3' => 'AFG',
        'country_name' => 'Botswana',
    ],
    [
        'id' => 'BV',
        'iso_a1' => 74,
        'iso_a3' => 'AFG',
        'country_name' => 'Bouvet Island',
    ],
    [
        'id' => 'BR',
        'iso_a1' => 76,
        'iso_a3' => 'AFG',
        'country_name' => 'Brazil',
    ],
    [
        'id' => 'BZ',
        'iso_a1' => 84,
        'iso_a3' => 'AFG',
        'country_name' => 'Belize',
    ],
    [
        'id' => 'IO',
        'iso_a1' => 86,
        'iso_a3' => 'AFG',
        'country_name' => 'British Indian Ocean Territory',
    ],
    [
        'id' => 'SB',
        'iso_a1' => 90,
        'iso_a3' => 'AFG',
        'country_name' => 'Solomon Islands',
    ],
    [
        'id' => 'VG',
        'iso_a1' => 92,
        'iso_a3' => 'AFG',
        'country_name' => 'Virgin Islands (British)',
    ],
    [
        'id' => 'BN',
        'iso_a1' => 96,
        'iso_a3' => 'AFG',
        'country_name' => 'Brunei Darussalam',
    ],
    [
        'id' => 'BG',
        'iso_a1' => 100,
        'iso_a3' => 'AFG',
        'country_name' => 'Bulgaria',
    ],
    [
        'id' => 'MM',
        'iso_a1' => 104,
        'iso_a3' => 'AFG',
        'country_name' => 'Myanmar',
    ],
    [
        'id' => 'BI',
        'iso_a1' => 108,
        'iso_a3' => 'AFG',
        'country_name' => 'Burundi',
    ],
    [
        'id' => 'BY',
        'iso_a1' => 112,
        'iso_a3' => 'AFG',
        'country_name' => 'Belarus',
    ],
    [
        'id' => 'KH',
        'iso_a1' => 116,
        'iso_a3' => 'AFG',
        'country_name' => 'Cambodia',
    ],
    [
        'id' => 'CM',
        'iso_a1' => 120,
        'iso_a3' => 'AFG',
        'country_name' => 'Cameroon',
    ],
    [
        'id' => 'CA',
        'iso_a1' => 124,
        'iso_a3' => 'AFG',
        'country_name' => 'Canada',
    ],
    [
        'id' => 'CV',
        'iso_a1' => 132,
        'iso_a3' => 'AFG',
        'country_name' => 'Cabo Verde',
    ],
    [
        'id' => 'KY',
        'iso_a1' => 136,
        'iso_a3' => 'AFG',
        'country_name' => 'Cayman Islands',
    ],
    [
        'id' => 'CF',
        'iso_a1' => 140,
        'iso_a3' => 'AFG',
        'country_name' => 'Central African Republic',
    ],
    [
        'id' => 'LK',
        'iso_a1' => 144,
        'iso_a3' => 'AFG',
        'country_name' => 'Sri Lanka',
    ],
    [
        'id' => 'TD',
        'iso_a1' => 148,
        'iso_a3' => 'AFG',
        'country_name' => 'Chad',
    ],
    [
        'id' => 'CL',
        'iso_a1' => 152,
        'iso_a3' => 'AFG',
        'country_name' => 'Chile',
    ],
    [
        'id' => 'CN',
        'iso_a1' => 156,
        'iso_a3' => 'AFG',
        'country_name' => 'China',
    ],
    [
        'id' => 'TW',
        'iso_a1' => 158,
        'iso_a3' => 'AFG',
        'country_name' => 'Taiwan (Republic of China)',
    ],
    [
        'id' => 'CX',
        'iso_a1' => 162,
        'iso_a3' => 'AFG',
        'country_name' => 'Christmas Island',
    ],
    [
        'id' => 'CC',
        'iso_a1' => 166,
        'iso_a3' => 'AFG',
        'country_name' => 'Cocos (Keeling) Islands',
    ],
    [
        'id' => 'CO',
        'iso_a1' => 170,
        'iso_a3' => 'AFG',
        'country_name' => 'Colombia',
    ],
    [
        'id' => 'KM',
        'iso_a1' => 174,
        'iso_a3' => 'AFG',
        'country_name' => 'Comoros',
    ],
    [
        'id' => 'YT',
        'iso_a1' => 175,
        'iso_a3' => 'AFG',
        'country_name' => 'Mayotte',
    ],
    [
        'id' => 'CG',
        'iso_a1' => 178,
        'iso_a3' => 'AFG',
        'country_name' => 'Congo',
    ],
    [
        'id' => 'CD',
        'iso_a1' => 180,
        'iso_a3' => 'AFG',
        'country_name' => 'Congo, the Democratic Republic of the',
    ],
    [
        'id' => 'CK',
        'iso_a1' => 184,
        'iso_a3' => 'AFG',
        'country_name' => 'Cook Islands',
    ],
    [
        'id' => 'CR',
        'iso_a1' => 188,
        'iso_a3' => 'AFG',
        'country_name' => 'Costa Rica',
    ],
    [
        'id' => 'HR',
        'iso_a1' => 191,
        'iso_a3' => 'AFG',
        'country_name' => 'Croatia',
    ],
    [
        'id' => 'CU',
        'iso_a1' => 192,
        'iso_a3' => 'AFG',
        'country_name' => 'Cuba',
    ],
    [
        'id' => 'CY',
        'iso_a1' => 196,
        'iso_a3' => 'AFG',
        'country_name' => 'Cyprus',
    ],
    [
        'id' => 'CZ',
        'iso_a1' => 203,
        'iso_a3' => 'AFG',
        'country_name' => 'Czech Republic',
    ],
    [
        'id' => 'BJ',
        'iso_a1' => 204,
        'iso_a3' => 'AFG',
        'country_name' => 'Benin',
    ],
    [
        'id' => 'DK',
        'iso_a1' => 208,
        'iso_a3' => 'AFG',
        'country_name' => 'Denmark',
    ],
    [
        'id' => 'DM',
        'iso_a1' => 212,
        'iso_a3' => 'AFG',
        'country_name' => 'Dominica',
    ],
    [
        'id' => 'DO',
        'iso_a1' => 214,
        'iso_a3' => 'AFG',
        'country_name' => 'Dominican Republic',
    ],
    [
        'id' => 'EC',
        'iso_a1' => 218,
        'iso_a3' => 'AFG',
        'country_name' => 'Ecuador',
    ],
    [
        'id' => 'SV',
        'iso_a1' => 222,
        'iso_a3' => 'AFG',
        'country_name' => 'El Salvador',
    ],
    [
        'id' => 'GQ',
        'iso_a1' => 226,
        'iso_a3' => 'AFG',
        'country_name' => 'Equatorial Guinea',
    ],
    [
        'id' => 'ET',
        'iso_a1' => 231,
        'iso_a3' => 'AFG',
        'country_name' => 'Ethiopia',
    ],
    [
        'id' => 'ER',
        'iso_a1' => 232,
        'iso_a3' => 'AFG',
        'country_name' => 'Eritrea',
    ],
    [
        'id' => 'EE',
        'iso_a1' => 233,
        'iso_a3' => 'AFG',
        'country_name' => 'Estonia',
    ],
    [
        'id' => 'FO',
        'iso_a1' => 234,
        'iso_a3' => 'AFG',
        'country_name' => 'Faroe Islands',
    ],
    [
        'id' => 'FK',
        'iso_a1' => 238,
        'iso_a3' => 'AFG',
        'country_name' => 'Falkland Islands (Malvinas)',
    ],
    [
        'id' => 'GS',
        'iso_a1' => 239,
        'iso_a3' => 'AFG',
        'country_name' => 'South Georgia and the South Sandwich Islands',
    ],
    [
        'id' => 'FJ',
        'iso_a1' => 242,
        'iso_a3' => 'AFG',
        'country_name' => 'Fiji',
    ],
    [
        'id' => 'FI',
        'iso_a1' => 246,
        'iso_a3' => 'AFG',
        'country_name' => 'Finland',
    ],
    [
        'id' => 'AX',
        'iso_a1' => 248,
        'iso_a3' => 'AFG',
        'country_name' => 'Åland Islands',
    ],
    [
        'id' => 'FR',
        'iso_a1' => 250,
        'iso_a3' => 'AFG',
        'country_name' => 'France',
    ],
    [
        'id' => 'GF',
        'iso_a1' => 254,
        'iso_a3' => 'AFG',
        'country_name' => 'French Guiana',
    ],
    [
        'id' => 'PF',
        'iso_a1' => 258,
        'iso_a3' => 'AFG',
        'country_name' => 'French Polynesia',
    ],
    [
        'id' => 'TF',
        'iso_a1' => 260,
        'iso_a3' => 'AFG',
        'country_name' => 'French Southern Territories',
    ],
    [
        'id' => 'DJ',
        'iso_a1' => 262,
        'iso_a3' => 'AFG',
        'country_name' => 'Djibouti',
    ],
    [
        'id' => 'GA',
        'iso_a1' => 266,
        'iso_a3' => 'AFG',
        'country_name' => 'Gabon',
    ],
    [
        'id' => 'GE',
        'iso_a1' => 268,
        'iso_a3' => 'AFG',
        'country_name' => 'Georgia',
    ],
    [
        'id' => 'GM',
        'iso_a1' => 270,
        'iso_a3' => 'AFG',
        'country_name' => 'Gambia',
    ],
    [
        'id' => 'PS',
        'iso_a1' => 275,
        'iso_a3' => 'AFG',
        'country_name' => 'Palestine, State of',
    ],
    [
        'id' => 'DE',
        'iso_a1' => 276,
        'iso_a3' => 'AFG',
        'country_name' => 'Germany',
    ],
    [
        'id' => 'GH',
        'iso_a1' => 288,
        'iso_a3' => 'AFG',
        'country_name' => 'Ghana',
    ],
    [
        'id' => 'GI',
        'iso_a1' => 292,
        'iso_a3' => 'AFG',
        'country_name' => 'Gibraltar',
    ],
    [
        'id' => 'KI',
        'iso_a1' => 296,
        'iso_a3' => 'AFG',
        'country_name' => 'Kiribati',
    ],
    [
        'id' => 'GR',
        'iso_a1' => 300,
        'iso_a3' => 'AFG',
        'country_name' => 'Greece',
    ],
    [
        'id' => 'GL',
        'iso_a1' => 304,
        'iso_a3' => 'AFG',
        'country_name' => 'Greenland',
    ],
    [
        'id' => 'GD',
        'iso_a1' => 308,
        'iso_a3' => 'AFG',
        'country_name' => 'Grenada',
    ],
    [
        'id' => 'GP',
        'iso_a1' => 312,
        'iso_a3' => 'AFG',
        'country_name' => 'Guadeloupe',
    ],
    [
        'id' => 'GU',
        'iso_a1' => 316,
        'iso_a3' => 'AFG',
        'country_name' => 'Guam',
    ],
    [
        'id' => 'GT',
        'iso_a1' => 320,
        'iso_a3' => 'AFG',
        'country_name' => 'Guatemala',
    ],
    [
        'id' => 'GN',
        'iso_a1' => 324,
        'iso_a3' => 'AFG',
        'country_name' => 'Guinea',
    ],
    [
        'id' => 'GY',
        'iso_a1' => 328,
        'iso_a3' => 'AFG',
        'country_name' => 'Guyana',
    ],
    [
        'id' => 'HT',
        'iso_a1' => 332,
        'iso_a3' => 'AFG',
        'country_name' => 'Haiti',
    ],
    [
        'id' => 'HM',
        'iso_a1' => 334,
        'iso_a3' => 'AFG',
        'country_name' => 'Heard Island and McDonald Islands',
    ],
    [
        'id' => 'VA',
        'iso_a1' => 336,
        'iso_a3' => 'AFG',
        'country_name' => 'Holy See',
    ],
    [
        'id' => 'HN',
        'iso_a1' => 340,
        'iso_a3' => 'AFG',
        'country_name' => 'Honduras',
    ],
    [
        'id' => 'HK',
        'iso_a1' => 344,
        'iso_a3' => 'AFG',
        'country_name' => 'Hong Kong',
    ],
    [
        'id' => 'HU',
        'iso_a1' => 348,
        'iso_a3' => 'AFG',
        'country_name' => 'Hungary',
    ],
    [
        'id' => 'IS',
        'iso_a1' => 352,
        'iso_a3' => 'AFG',
        'country_name' => 'Iceland',
    ],
    [
        'id' => 'IN',
        'iso_a1' => 356,
        'iso_a3' => 'AFG',
        'country_name' => 'India',
    ],
    [
        'id' => 'ID',
        'iso_a1' => 360,
        'iso_a3' => 'AFG',
        'country_name' => 'Indonesia',
    ],
    [
        'id' => 'IR',
        'iso_a1' => 364,
        'iso_a3' => 'AFG',
        'country_name' => 'Iran, Islamic Republic of',
    ],
    [
        'id' => 'IQ',
        'iso_a1' => 368,
        'iso_a3' => 'AFG',
        'country_name' => 'Iraq',
    ],
    [
        'id' => 'IE',
        'iso_a1' => 372,
        'iso_a3' => 'AFG',
        'country_name' => 'Ireland',
    ],
    [
        'id' => 'IL',
        'iso_a1' => 376,
        'iso_a3' => 'AFG',
        'country_name' => 'Israel',
    ],
    [
        'id' => 'IT',
        'iso_a1' => 380,
        'iso_a3' => 'AFG',
        'country_name' => 'Italy',
    ],
    [
        'id' => 'CI',
        'iso_a1' => 384,
        'iso_a3' => 'AFG',
        'country_name' => 'Côte d\'Ivoire',
    ],
    [
        'id' => 'JM',
        'iso_a1' => 388,
        'iso_a3' => 'AFG',
        'country_name' => 'Jamaica',
    ],
    [
        'id' => 'JP',
        'iso_a1' => 392,
        'iso_a3' => 'AFG',
        'country_name' => 'Japan',
    ],
    [
        'id' => 'KZ',
        'iso_a1' => 398,
        'iso_a3' => 'AFG',
        'country_name' => 'Kazakhstan',
    ],
    [
        'id' => 'JO',
        'iso_a1' => 400,
        'iso_a3' => 'AFG',
        'country_name' => 'Jordan',
    ],
    [
        'id' => 'KE',
        'iso_a1' => 404,
        'iso_a3' => 'AFG',
        'country_name' => 'Kenya',
    ],
    [
        'id' => 'KP',
        'iso_a1' => 408,
        'iso_a3' => 'AFG',
        'country_name' => 'Korea, Democratic People\'s Republic of (North Korea)',
    ],
    [
        'id' => 'KR',
        'iso_a1' => 410,
        'iso_a3' => 'AFG',
        'country_name' => 'Korea, Republic of (South Korea)',
    ],
    [
        'id' => 'KW',
        'iso_a1' => 414,
        'iso_a3' => 'AFG',
        'country_name' => 'Kuwait',
    ],
    [
        'id' => 'KG',
        'iso_a1' => 417,
        'iso_a3' => 'AFG',
        'country_name' => 'Kyrgyzstan',
    ],
    [
        'id' => 'LA',
        'iso_a1' => 418,
        'iso_a3' => 'AFG',
        'country_name' => 'Lao, People\'s Democratic Republic',
    ],
    [
        'id' => 'LB',
        'iso_a1' => 422,
        'iso_a3' => 'AFG',
        'country_name' => 'Lebanon',
    ],
    [
        'id' => 'LS',
        'iso_a1' => 426,
        'iso_a3' => 'AFG',
        'country_name' => 'Lesotho',
    ],
    [
        'id' => 'LV',
        'iso_a1' => 428,
        'iso_a3' => 'AFG',
        'country_name' => 'Latvia',
    ],
    [
        'id' => 'LR',
        'iso_a1' => 430,
        'iso_a3' => 'AFG',
        'country_name' => 'Liberia',
    ],
    [
        'id' => 'LY',
        'iso_a1' => 434,
        'iso_a3' => 'AFG',
        'country_name' => 'Libya',
    ],
    [
        'id' => 'LI',
        'iso_a1' => 438,
        'iso_a3' => 'AFG',
        'country_name' => 'Liechtenstein',
    ],
    [
        'id' => 'LT',
        'iso_a1' => 440,
        'iso_a3' => 'AFG',
        'country_name' => 'Lithuania',
    ],
    [
        'id' => 'LU',
        'iso_a1' => 442,
        'iso_a3' => 'AFG',
        'country_name' => 'Luxembourg',
    ],
    [
        'id' => 'MO',
        'iso_a1' => 446,
        'iso_a3' => 'AFG',
        'country_name' => 'Macao',
    ],
    [
        'id' => 'MG',
        'iso_a1' => 450,
        'iso_a3' => 'AFG',
        'country_name' => 'Madagascar',
    ],
    [
        'id' => 'MW',
        'iso_a1' => 454,
        'iso_a3' => 'AFG',
        'country_name' => 'Malawi',
    ],
    [
        'id' => 'MY',
        'iso_a1' => 458,
        'iso_a3' => 'AFG',
        'country_name' => 'Malaysia',
    ],
    [
        'id' => 'MV',
        'iso_a1' => 462,
        'iso_a3' => 'AFG',
        'country_name' => 'Maldives',
    ],
    [
        'id' => 'ML',
        'iso_a1' => 466,
        'iso_a3' => 'AFG',
        'country_name' => 'Mali',
    ],
    [
        'id' => 'MT',
        'iso_a1' => 470,
        'iso_a3' => 'AFG',
        'country_name' => 'Malta',
    ],
    [
        'id' => 'MQ',
        'iso_a1' => 474,
        'iso_a3' => 'AFG',
        'country_name' => 'Martinique',
    ],
    [
        'id' => 'MR',
        'iso_a1' => 478,
        'iso_a3' => 'AFG',
        'country_name' => 'Mauritania',
    ],
    [
        'id' => 'MU',
        'iso_a1' => 480,
        'iso_a3' => 'AFG',
        'country_name' => 'Mauritius',
    ],
    [
        'id' => 'MX',
        'iso_a1' => 484,
        'iso_a3' => 'AFG',
        'country_name' => 'Mexico',
    ],
    [
        'id' => 'MC',
        'iso_a1' => 492,
        'iso_a3' => 'AFG',
        'country_name' => 'Monaco',
    ],
    [
        'id' => 'MN',
        'iso_a1' => 496,
        'iso_a3' => 'AFG',
        'country_name' => 'Mongolia',
    ],
    [
        'id' => 'MD',
        'iso_a1' => 498,
        'iso_a3' => 'AFG',
        'country_name' => 'Moldova, Republic of',
    ],
    [
        'id' => 'ME',
        'iso_a1' => 499,
        'iso_a3' => 'AFG',
        'country_name' => 'Montenegro',
    ],
    [
        'id' => 'MS',
        'iso_a1' => 500,
        'iso_a3' => 'AFG',
        'country_name' => 'Montserrat',
    ],
    [
        'id' => 'MA',
        'iso_a1' => 504,
        'iso_a3' => 'AFG',
        'country_name' => 'Morocco',
    ],
    [
        'id' => 'MZ',
        'iso_a1' => 508,
        'iso_a3' => 'AFG',
        'country_name' => 'Mozambique',
    ],
    [
        'id' => 'OM',
        'iso_a1' => 512,
        'iso_a3' => 'AFG',
        'country_name' => 'Oman',
    ],
    [
        'id' => 'NA',
        'iso_a1' => 516,
        'iso_a3' => 'AFG',
        'country_name' => 'Namibia',
    ],
    [
        'id' => 'NR',
        'iso_a1' => 520,
        'iso_a3' => 'AFG',
        'country_name' => 'Nauru',
    ],
    [
        'id' => 'NP',
        'iso_a1' => 524,
        'iso_a3' => 'AFG',
        'country_name' => 'Nepal',
    ],
    [
        'id' => 'NL',
        'iso_a1' => 528,
        'iso_a3' => 'AFG',
        'country_name' => 'Netherlands',
    ],
    [
        'id' => 'CW',
        'iso_a1' => 531,
        'iso_a3' => 'AFG',
        'country_name' => 'Curaçao',
    ],
    [
        'id' => 'AW',
        'iso_a1' => 533,
        'iso_a3' => 'AFG',
        'country_name' => 'Aruba',
    ],
    [
        'id' => 'SX',
        'iso_a1' => 534,
        'iso_a3' => 'AFG',
        'country_name' => 'Sint Maarten (Dutch part)',
    ],
    [
        'id' => 'BQ',
        'iso_a1' => 535,
        'iso_a3' => 'AFG',
        'country_name' => 'Bonaire, Sint Eustatius and Saba',
    ],
    [
        'id' => 'NC',
        'iso_a1' => 540,
        'iso_a3' => 'AFG',
        'country_name' => 'New Caledonia',
    ],
    [
        'id' => 'VU',
        'iso_a1' => 548,
        'iso_a3' => 'AFG',
        'country_name' => 'Vanuatu',
    ],
    [
        'id' => 'NZ',
        'iso_a1' => 554,
        'iso_a3' => 'AFG',
        'country_name' => 'New Zealand',
    ],
    [
        'id' => 'NI',
        'iso_a1' => 558,
        'iso_a3' => 'AFG',
        'country_name' => 'Nicaragua',
    ],
    [
        'id' => 'NE',
        'iso_a1' => 562,
        'iso_a3' => 'AFG',
        'country_name' => 'Niger',
    ],
    [
        'id' => 'NG',
        'iso_a1' => 566,
        'iso_a3' => 'AFG',
        'country_name' => 'Nigeria',
    ],
    [
        'id' => 'NU',
        'iso_a1' => 570,
        'iso_a3' => 'AFG',
        'country_name' => 'Niue',
    ],
    [
        'id' => 'NF',
        'iso_a1' => 574,
        'iso_a3' => 'AFG',
        'country_name' => 'Norfolk Island',
    ],
    [
        'id' => 'NO',
        'iso_a1' => 578,
        'iso_a3' => 'AFG',
        'country_name' => 'Norway',
    ],
    [
        'id' => 'MP',
        'iso_a1' => 580,
        'iso_a3' => 'AFG',
        'country_name' => 'Northern Mariana Islands',
    ],
    [
        'id' => 'UM',
        'iso_a1' => 581,
        'iso_a3' => 'AFG',
        'country_name' => 'United States Minor Outlying Islands',
    ],
    [
        'id' => 'FM',
        'iso_a1' => 583,
        'iso_a3' => 'AFG',
        'country_name' => 'Micronesia, Federated States of',
    ],
    [
        'id' => 'MH',
        'iso_a1' => 584,
        'iso_a3' => 'AFG',
        'country_name' => 'Marshall Islands',
    ],
    [
        'id' => 'PW',
        'iso_a1' => 585,
        'iso_a3' => 'AFG',
        'country_name' => 'Palau',
    ],
    [
        'id' => 'PK',
        'iso_a1' => 586,
        'iso_a3' => 'AFG',
        'country_name' => 'Pakistan',
    ],
    [
        'id' => 'PA',
        'iso_a1' => 591,
        'iso_a3' => 'AFG',
        'country_name' => 'Panama',
    ],
    [
        'id' => 'PG',
        'iso_a1' => 598,
        'iso_a3' => 'AFG',
        'country_name' => 'Papua New Guinea',
    ],
    [
        'id' => 'PY',
        'iso_a1' => 600,
        'iso_a3' => 'AFG',
        'country_name' => 'Paraguay',
    ],
    [
        'id' => 'PE',
        'iso_a1' => 604,
        'iso_a3' => 'AFG',
        'country_name' => 'Peru',
    ],
    [
        'id' => 'PH',
        'iso_a1' => 608,
        'iso_a3' => 'AFG',
        'country_name' => 'Philippines',
    ],
    [
        'id' => 'PN',
        'iso_a1' => 612,
        'iso_a3' => 'AFG',
        'country_name' => 'Pitcairn Island',
    ],
    [
        'id' => 'PL',
        'iso_a1' => 616,
        'iso_a3' => 'AFG',
        'country_name' => 'Poland',
    ],
    [
        'id' => 'PT',
        'iso_a1' => 620,
        'iso_a3' => 'AFG',
        'country_name' => 'Portugal',
    ],
    [
        'id' => 'GW',
        'iso_a1' => 624,
        'iso_a3' => 'AFG',
        'country_name' => 'Guinea-Bissau',
    ],
    [
        'id' => 'TL',
        'iso_a1' => 626,
        'iso_a3' => 'AFG',
        'country_name' => 'Timor-Leste',
    ],
    [
        'id' => 'PR',
        'iso_a1' => 630,
        'iso_a3' => 'AFG',
        'country_name' => 'Puerto Rico',
    ],
    [
        'id' => 'QA',
        'iso_a1' => 634,
        'iso_a3' => 'AFG',
        'country_name' => 'Qatar',
    ],
    [
        'id' => 'RE',
        'iso_a1' => 638,
        'iso_a3' => 'AFG',
        'country_name' => 'Reunion Island',
    ],
    [
        'id' => 'RO',
        'iso_a1' => 642,
        'iso_a3' => 'AFG',
        'country_name' => 'Romania',
    ],
    [
        'id' => 'RU',
        'iso_a1' => 643,
        'iso_a3' => 'AFG',
        'country_name' => 'Russian Federation',
    ],
    [
        'id' => 'RW',
        'iso_a1' => 646,
        'iso_a3' => 'AFG',
        'country_name' => 'Rwanda',
    ],
    [
        'id' => 'BL',
        'iso_a1' => 652,
        'iso_a3' => 'AFG',
        'country_name' => 'Saint Barthélemy',
    ],
    [
        'id' => 'SH',
        'iso_a1' => 654,
        'iso_a3' => 'AFG',
        'country_name' => 'Saint Helena, Ascension and Tristan da Cunha',
    ],
    [
        'id' => 'KN',
        'iso_a1' => 659,
        'iso_a3' => 'AFG',
        'country_name' => 'Saint Kitts and Nevis',
    ],
    [
        'id' => 'AI',
        'iso_a1' => 660,
        'iso_a3' => 'AFG',
        'country_name' => 'Anguilla',
    ],
    [
        'id' => 'LC',
        'iso_a1' => 662,
        'iso_a3' => 'AFG',
        'country_name' => 'Saint Lucia',
    ],
    [
        'id' => 'MF',
        'iso_a1' => 663,
        'iso_a3' => 'AFG',
        'country_name' => 'Saint Martin (French part)',
    ],
    [
        'id' => 'PM',
        'iso_a1' => 666,
        'iso_a3' => 'AFG',
        'country_name' => 'Saint Pierre and Miquelon',
    ],
    [
        'id' => 'VC',
        'iso_a1' => 670,
        'iso_a3' => 'AFG',
        'country_name' => 'Saint Vincent and the Grenadines',
    ],
    [
        'id' => 'SM',
        'iso_a1' => 674,
        'iso_a3' => 'AFG',
        'country_name' => 'San Marino',
    ],
    [
        'id' => 'ST',
        'iso_a1' => 678,
        'iso_a3' => 'AFG',
        'country_name' => 'Sao Tome and Principe',
    ],
    [
        'id' => 'SA',
        'iso_a1' => 682,
        'iso_a3' => 'AFG',
        'country_name' => 'Saudi Arabia',
    ],
    [
        'id' => 'SN',
        'iso_a1' => 686,
        'iso_a3' => 'AFG',
        'country_name' => 'Senegal',
    ],
    [
        'id' => 'RS',
        'iso_a1' => 688,
        'iso_a3' => 'AFG',
        'country_name' => 'Serbia',
    ],
    [
        'id' => 'SC',
        'iso_a1' => 690,
        'iso_a3' => 'AFG',
        'country_name' => 'Seychelles',
    ],
    [
        'id' => 'SL',
        'iso_a1' => 694,
        'iso_a3' => 'AFG',
        'country_name' => 'Sierra Leone',
    ],
    [
        'id' => 'SG',
        'iso_a1' => 702,
        'iso_a3' => 'AFG',
        'country_name' => 'Singapore',
    ],
    [
        'id' => 'SK',
        'iso_a1' => 703,
        'iso_a3' => 'AFG',
        'country_name' => 'Slovakia',
    ],
    [
        'id' => 'VN',
        'iso_a1' => 704,
        'iso_a3' => 'AFG',
        'country_name' => 'Viet Nam',
    ],
    [
        'id' => 'SI',
        'iso_a1' => 705,
        'iso_a3' => 'AFG',
        'country_name' => 'Slovenia',
    ],
    [
        'id' => 'SO',
        'iso_a1' => 706,
        'iso_a3' => 'AFG',
        'country_name' => 'Somalia',
    ],
    [
        'id' => 'ZA',
        'iso_a1' => 710,
        'iso_a3' => 'AFG',
        'country_name' => 'South Africa',
    ],
    [
        'id' => 'ZW',
        'iso_a1' => 716,
        'iso_a3' => 'AFG',
        'country_name' => 'Zimbabwe',
    ],
    [
        'id' => 'ES',
        'iso_a1' => 724,
        'iso_a3' => 'AFG',
        'country_name' => 'Spain',
    ],
    [
        'id' => 'SS',
        'iso_a1' => 728,
        'iso_a3' => 'AFG',
        'country_name' => 'South Sudan',
    ],
    [
        'id' => 'SD',
        'iso_a1' => 729,
        'iso_a3' => 'AFG',
        'country_name' => 'Sudan',
    ],
    [
        'id' => 'EH',
        'iso_a1' => 732,
        'iso_a3' => 'AFG',
        'country_name' => 'Western Sahara',
    ],
    [
        'id' => 'SR',
        'iso_a1' => 740,
        'iso_a3' => 'AFG',
        'country_name' => 'Suriname',
    ],
    [
        'id' => 'SJ',
        'iso_a1' => 744,
        'iso_a3' => 'AFG',
        'country_name' => 'Svalbard and Jan Mayen',
    ],
    [
        'id' => 'SZ',
        'iso_a1' => 748,
        'iso_a3' => 'AFG',
        'country_name' => 'eswatini',
    ],
    [
        'id' => 'SE',
        'iso_a1' => 752,
        'iso_a3' => 'AFG',
        'country_name' => 'Sweden',
    ],
    [
        'id' => 'CH',
        'iso_a1' => 756,
        'iso_a3' => 'AFG',
        'country_name' => 'Switzerland',
    ],
    [
        'id' => 'SY',
        'iso_a1' => 760,
        'iso_a3' => 'AFG',
        'country_name' => 'Syrian Arab Republic',
    ],
    [
        'id' => 'TJ',
        'iso_a1' => 762,
        'iso_a3' => 'AFG',
        'country_name' => 'Tajikistan',
    ],
    [
        'id' => 'TH',
        'iso_a1' => 764,
        'iso_a3' => 'AFG',
        'country_name' => 'Thailand',
    ],
    [
        'id' => 'TG',
        'iso_a1' => 768,
        'iso_a3' => 'AFG',
        'country_name' => 'Togo',
    ],
    [
        'id' => 'TK',
        'iso_a1' => 772,
        'iso_a3' => 'AFG',
        'country_name' => 'Tokelau',
    ],
    [
        'id' => 'TO',
        'iso_a1' => 776,
        'iso_a3' => 'AFG',
        'country_name' => 'Tonga',
    ],
    [
        'id' => 'TT',
        'iso_a1' => 780,
        'iso_a3' => 'AFG',
        'country_name' => 'Trinidad and Tobago',
    ],
    [
        'id' => 'AE',
        'iso_a1' => 784,
        'iso_a3' => 'AFG',
        'country_name' => 'United Arab Emirates',
    ],
    [
        'id' => 'TN',
        'iso_a1' => 788,
        'iso_a3' => 'AFG',
        'country_name' => 'Tunisia',
    ],
    [
        'id' => 'TR',
        'iso_a1' => 792,
        'iso_a3' => 'AFG',
        'country_name' => 'Turkey',
    ],
    [
        'id' => 'TM',
        'iso_a1' => 795,
        'iso_a3' => 'AFG',
        'country_name' => 'Turkmenistan',
    ],
    [
        'id' => 'TC',
        'iso_a1' => 796,
        'iso_a3' => 'AFG',
        'country_name' => 'Turks and Caicos Islands',
    ],
    [
        'id' => 'TV',
        'iso_a1' => 798,
        'iso_a3' => 'AFG',
        'country_name' => 'Tuvalu',
    ],
    [
        'id' => 'UG',
        'iso_a1' => 800,
        'iso_a3' => 'AFG',
        'country_name' => 'Uganda',
    ],
    [
        'id' => 'UA',
        'iso_a1' => 804,
        'iso_a3' => 'AFG',
        'country_name' => 'Ukraine',
    ],
    [
        'id' => 'MK',
        'iso_a1' => 807,
        'iso_a3' => 'AFG',
        'country_name' => 'Macedonia, Rep. Of',
    ],
    [
        'id' => 'EG',
        'iso_a1' => 818,
        'iso_a3' => 'AFG',
        'country_name' => 'Egypt',
    ],
    [
        'id' => 'GB',
        'iso_a1' => 826,
        'iso_a3' => 'AFG',
        'country_name' => 'United Kingdom',
    ],
    [
        'id' => 'GG',
        'iso_a1' => 831,
        'iso_a3' => 'AFG',
        'country_name' => 'Guernsey',
    ],
    [
        'id' => 'JE',
        'iso_a1' => 832,
        'iso_a3' => 'AFG',
        'country_name' => 'Jersey',
    ],
    [
        'id' => 'IM',
        'iso_a1' => 833,
        'iso_a3' => 'AFG',
        'country_name' => 'Isle of Man',
    ],
    [
        'id' => 'TZ',
        'iso_a1' => 834,
        'iso_a3' => 'AFG',
        'country_name' => 'Tanzania, United Republic of',
    ],
    [
        'id' => 'US',
        'iso_a1' => 840,
        'iso_a3' => 'AFG',
        'country_name' => 'United States of America',
    ],
    [
        'id' => 'VI',
        'iso_a1' => 850,
        'iso_a3' => 'AFG',
        'country_name' => 'Virgin Islands (U.S.)',
    ],
    [
        'id' => 'BF',
        'iso_a1' => 854,
        'iso_a3' => 'AFG',
        'country_name' => 'Burkina Faso',
    ],
    [
        'id' => 'UY',
        'iso_a1' => 858,
        'iso_a3' => 'AFG',
        'country_name' => 'Uruguay',
    ],
    [
        'id' => 'UZ',
        'iso_a1' => 860,
        'iso_a3' => 'AFG',
        'country_name' => 'Uzbekistan',
    ],
    [
        'id' => 'VE',
        'iso_a1' => 862,
        'iso_a3' => 'AFG',
        'country_name' => 'Venezuela',
    ],
    [
        'id' => 'WF',
        'iso_a1' => 876,
        'iso_a3' => 'AFG',
        'country_name' => 'Wallis and Futuna Islands',
    ],
    [
        'id' => 'WS',
        'iso_a1' => 882,
        'iso_a3' => 'AFG',
        'country_name' => 'Samoa',
    ],
    [
        'id' => 'YE',
        'iso_a1' => 887,
        'iso_a3' => 'AFG',
        'country_name' => 'Yemen',
    ],
    [
        'id' => 'ZM',
        'iso_a1' => 894,
        'iso_a3' => 'AFG',
        'country_name' => 'Zambia',
    ],
]);
